### ISSUE TITLE
db: dataset result downloads take a long time

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#389]
* specifically, for the new 'large' dataset http://lincs.hms.harvard.edu/db/datasets/20236/results
* the process could be sped up, I believe, if we wrote the output file to a temp directory on disk before streaming through the HTTP response: here https://github.com/hmslincs/hmslincs/blob/master/django/db/views.py#L2371
* also, caching the download could be useful

**Comment by jmuhlich** [comment]
Why might writing a temp file to disk be faster? From my reading of openpyxl.writer.excel.save_virtual_workbook it's running effectively the same code as save_workbook except writing to an io.BytesIO rather than an actual file. Performance claims need benchmarks/profiling/etc. to back them up!

I do agree caching would be a good solution if the export code can't be sped up.

**Comment by seanderickson** [comment]
good point
- the openpyxl in "optimized" write mode writes in a streaming fashion and improves the view xlsx download time.
- for the api download; it looks like the query efficiency will need to be improved.
