### ISSUE TITLE
db: compound image overlaps the compound title in compound detail

### ISSUE THREAD

**Issue by seanderickson** [hmslincs/hmslincs#396]
see: http://lincs.hms.harvard.edu/db/sm/10001-101/

- image is positioned using absolute coordinates (should use relative?)
- addition of the "article_type" element above the "inner_content" element has pushed the inner_content down

@jmuhlich

**Comment by jmuhlich** [comment]
Right. But remember that "absolute" is in terms of the "nearest 
positioned ancestor". In this case that's #content which has "position: 
relative". It could be made relative to #innercontent instead simply by 
adding "#innercontent { position: relative; }" to the CSS. The offsets 
of the img (right and top) would probably need to be tweaked.

Ideally the img should be relative to .detail_table but that would 
require a little more HTML surgery. For example the img could be moved 
into a table cell and then .detail_table could be assigned "position: 
relative". Aiming for progressive enhancement, the img should go in a 
reasonable place in the table assuming no CSS, so maybe in the cell with 
the name could work. Even better would be to put it in its own row, but 
that complicates things even further as that row would need to be hidden 
with CSS since the img will be visually removed from it with its own CSS.
